# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md", "Makefile", "Gemfile", "Gemfile.lock"]
highlighter: rouge

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : Marc LaFleur
author :
  name : Marc LaFleur
  email : marcla@microsoft.com
  github : mlafleur
  twitter : mlafleur
  feedburner : nil

production_url : http://mlafleur.github.io

# Tell Github to use the kramdown markdown interpreter
# (see https://help.github.com/articles/migrating-your-pages-site-from-maruku)
markdown: kramdown

paginate: 5
paginate_path: "/blog/page:num/"